# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-15 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topics',
            new_name='Topic',
        ),
        migrations.RenameModel(
            old_name='Webpages',
            new_name='Webpage',
        ),
    ]
